name: test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: installdeps
      run: sudo ./build.sh installdeps
    - name: build
      run: |
        if ! ./build.sh test
        then
          debug/bin/unit_test
        fi
